#! /bin/sh
CGIPARSE=/usr/people/ishii/cgi-bin/cgiparse
CGIUTILS=/usr/people/ishii/cgi-bin/cgiutils
$CGIUTILS -expires now -ct text/html
eval `$CGIPARSE -init`
eval `$CGIPARSE -form`

exec /disk2/usr/postgres/bin/pgtclsh /usr/people/ishii/cgi-bin/view_table.tcl $FORM_hostname $FORM_dbname $FORM_table_name
